### ISSUE TITLE
请教如何加入一个新的产品，比如袋鼠

### ISSUE THREAD

**Issue by yylaji** [summersky2014/snap-up#1]
https://item.jd.com/100006394713.html
这是袋鼠抢购的链接，直接在TASK.Js修改，仿照3Q口罩，问题是，两个时间一样，没啥冲突吧

**Comment by summersky2014** [comment]
对的，修改task.ts文件就可以。
已经把单标签页改为了多标签页，可以同时进行多个同一时间的抢购或预约
